package com.pda.task.domain;

/** What happened on a task; stored as text in task_activities. */
public enum ActivityType {
    CREATED, FIELD_CHANGED, STATUS_CHANGED, BLOCKED, UNBLOCKED, ASSIGNED, UNASSIGNED,
    POOL_OPENED, POOL_CLOSED, CLAIMED, RELEASED, LABELS_CHANGED, SPRINT_CHANGED, PARENT_CHANGED,
    SUBTASK_ADDED, CHECKLIST_ITEM_ADDED, CHECKLIST_ITEM_DONE, CHECKLIST_ITEM_REOPENED,
    RELATION_ADDED, RELATION_REMOVED, ATTACHMENT_ADDED, ATTACHMENT_REMOVED, WORKLOG_ADDED, ARCHIVED
}
