package com.pda.notification.domain;

public enum NotificationType {
    TASK_ASSIGNED, TASK_UNASSIGNED, TASK_STATUS_CHANGED, TASK_PRIORITY_CHANGED,
    TASK_DUE_DATE_CHANGED, TASK_BLOCKED, PROJECT_MEMBER_ADDED, PROJECT_MEMBER_REMOVED,
    PROJECT_ROLE_CHANGED, SQUAD_MEMBER_ADDED, SQUAD_MEMBER_REMOVED, SQUAD_DELETED,
    PROJECT_INVITATION_CREATED, PROJECT_INVITATION_ACCEPTED, PROJECT_INVITATION_REJECTED,
    TASK_DEADLINE_SOON, TASK_OVERDUE, TASK_CLAIMED, TASK_RELEASED, TASK_MENTIONED, TASK_COMMENTED
}
